### ISSUE TITLE
is there any way to extend the maximum depth beyond 310 km upto 1000 km?

### ISSUE THREAD

**Issue by ad1995-geek** [cmeessen/VelocityConversion#3]

**Comment by cmeessen** [comment]
Yes, you could do that by extending the reference model array. However, already the depth of the reference model of 310km exceeds the range where the used physical model is considered to be a reasonable approximation (which is up to about 200km). This means, converted velocities and densities are not reliable anymore. See the original publication by [Goes et al. (2000)](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/1999JB900300).
