### ISSUE TITLE
velocity to density conversion giving absurd results at deeper deth?

### ISSUE THREAD

**Issue by ad1995-geek** [cmeessen/VelocityConversion#6]
I am using gypsum velocity model for density conversion. I have extended the depth  range up to 1500 km in AK135 model. I am getting good result up to 414 km. But below this depth giving absurd results? could you give me some suggestion , Why this code not giving good result in deeper depth?

**Comment by cmeessen** [comment]
Please refer to the publication of [Goes et al. (2000)](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/1999JB900300) regarding the used methodology for the conversion of velocities to densities. The method is not applicable for depths much greater than 200 km.
